<?php include 'header.php' ?>

<div class="container pt-5 pb-5 text-center">
	<div class="row">
		<div class="col">
			<!-- Image Map Generated by http://www.image-map.net/ -->
<h2 class="pt-2 pb-1 bg-light">Touch Area You Want to Train</h2>  <hr class="pb-2">          
<img src="asset/images/workout1.pn
g" usemap="#image-map">

<map name="image-map">
    <area target="_parent" alt="Chest" title="Chest" href="http://localhost/fitbee/exercises.php?t=Chest" coords="505,293,33" shape="circle">
    <area target="_parent" alt="Arms" title="Arms" href="http://localhost/fitbee/exercises.php?t=Arms" coords="395,342,22" shape="circle">
    <area target="_parent" alt="Arms" title="Arms" href="http://localhost/fitbee/exercises.php?t=Arms" coords="605,344,23" shape="circle">
    <area target="_parent" alt="Shoulders" title="Shoulders" href="http://localhost/fitbee/exercises.php?t=Shoulders" coords="409,226,19" shape="circle">
    <area target="_parent" alt="Shoulders" title="Shoulders" href="http://localhost/fitbee/exercises.php?t=Shoulders" coords="584,223,19" shape="circle">
    <area target="_parent" alt="Back" title="Back" href="http://localhost/fitbee/exercises.php?t=Back" coords="562,394,16" shape="circle">
    <area target="_parent" alt="Abdominal" title="Abdominal" href="http://localhost/fitbee/exercises.php?t=Abdominal" coords="497,446,46" shape="circle">
    <area target="_parent" alt="Legs" title="Legs" href="http://localhost/fitbee/exercises.php?t=Legs" coords="455,619,34" shape="circle">
    <area target="_parent" alt="Legs" title="Legs" href="http://localhost/fitbee/exercises.php?t=Legs" coords="550,759,24" shape="circle">
</map>
		</div>
	</div>
</div>		
<?php include 'footer.php' ?>



